// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3BIDSYCNTohjBw-eKUnjUmmGyVo7aQTQ',
    appId: '1:153795589671:web:ac5d71e98b97b57a614002',
    messagingSenderId: '153795589671',
    projectId: 'mood-tracker-raom',
    authDomain: 'mood-tracker-raom.firebaseapp.com',
    storageBucket: 'mood-tracker-raom.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARI2U88BJeskzsBi6z_dk9RKZIPVG3dCY',
    appId: '1:153795589671:android:c20351f412d7ea93614002',
    messagingSenderId: '153795589671',
    projectId: 'mood-tracker-raom',
    storageBucket: 'mood-tracker-raom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_Cq6q7B8HBq9mrcBK-fiT7XFDudiGjZo',
    appId: '1:153795589671:ios:e12bf6a400132071614002',
    messagingSenderId: '153795589671',
    projectId: 'mood-tracker-raom',
    storageBucket: 'mood-tracker-raom.appspot.com',
    iosBundleId: 'com.example.moodTracker',
  );
}
